version: "3"
services:
  api:
    build: api
    environment:
      DB_URL: 'sqlite+aiosqlite:////dbdata/api.db'
      MAX_WORKERS: "1" # race condition with multiple workers?
    volumes:
      - db-data:/dbdata
  frontend:
    build: frontend
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
volumes:
  db-data:
